### PR TITLE
[WIP]: TODO list for Python 3 compatibility

### PR DESCRIPTION
**Pull request by cclauss**
__Do NOT merge.__  Much work to do before infogami is Python 3 compatible
* [x] ~#5 Modernize python 2 codes~ incorporated in #9
* [x] ~#9 [WIP] Travis CI updates~
* [x] ~#10 urllib.basejoin() was replaced by urljoin in Python 2.4~ incorporated in #9
* [ ] markdown.py: unicode and basestring were removed in Python 3
    * Or [__pip install Markdown__](https://github.com/Python-Markdown/markdown/) instead
* [x] #38 Use raw strings to prevent the final python3 syntax error
* [x] #39 Fix execfile() and basestring for Python 3
* [x] Fix __unicode__ for Python 3 (similar to #39)
* [x] Work through [Travis CI's](https://travis-ci.org/internetarchive/infogami) Flake8 and pytest results until they are clean on both Python 2 and 3
* [ ] Revisit dependencies and imports
    * [ ] Double check with both https://pypi.org/project/modernize and https://pypi.org/project/future
* [ ] Merge this PR.

The following should be reviewed once #9 has been merged:
* [x] internetarchive/openlibrary#2320 Start testing this code on Python 3 in OL in __allow_failures__ mode
* [ ] infogami/infogami#3 Undefined names in Python code
* [x] infogami/infogami#4 Pytest is failing because 'app' is undefined in delegate.py
* [ ] infogami/infogami#5 Remove OrderedDict and DefaultDict from infogami/utils/storage.py 
* [ ] infogami/infogami#6 MutableMapping is not a 100% replacement for DictMixin

### CODE REVIEW

**Comment by hornc** [comment]
I believe #9 resolves infogami#6 and infogami#4. I did not address 5, but that should get done at some point too.

**Comment by cclauss** [comment]
1. I believe that syntax errors (flake8 E999) on Python 2 should take priority over pytest unless there is a simple way to get pytest working again on Python 2.
2. Syntax errors (flake8 E999) on Python 3 should be next in line.
3. Undefined names (flake8 F821) and/or pytests should be next in line.
4. Once Python 2 is passing both flake8 tests and pytests we can start in earnest on Python 3.

I worry about current PRs that attempt to change 62 files in a single PR.

Currently __python2 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__ returns:
```
1     E999 IndentationError: unexpected unindent
217   F821 undefined name 'cache'
```
Currently __python3 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__ returns:
```
2     E999 SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: malformed \N character escape
221   F821 undefined name 'cache'
```

**Comment by cclauss** [comment]
Updated the list a the top of this PR.

**Comment by cclauss** [comment]
On Python 2 flake8 finds 3 undefined names.
On Python 3 flake8 finds 1 syntax error and 37 undefined names.

**Comment by cclauss** [comment]
Closing in favor of  #43

**Pull request closed without merging**
