### PR TITLE
 Remove try: block that has no matching except: block 

### PR DESCRIPTION
**Pull request by cclauss**
Resolves the last Python 2 syntax error so add E999 to the mandatory flake8 tests in our Travis CI automated testing.

### CODE REVIEW

**Comment by cclauss** [comment]
I am hiking in the mountains today but I should get to look at this in 24 hours.

**Comment by cclauss** [comment]
OK...  Are we going to work on __internetarchive/infogami__ or __infogami/infogami__?

I am not a fan of a _separate_ Python 3 branch.  It is safer to have a single master branch that passes the tests on both Python 2 and Python 3 so that we can do A/B testing on a single codebase.

We should focus first on getting Python 2 to pass both flake8 and pytests.  After that is done we should get Python 3 to pass flake8 tests without breaking the Python 2 tests. Finally we should get Python 3 to pass the pytests without breaking the Python 2 tests or the flake8 tests.  Sound right?

**Comment by hornc** [comment]
Yes! Thank you! That is in line with what we (Open Library community) have recently decided. We are now committing to moving forward with Python 3 compatibility in this forked repo to support OL.

Getting this codebase in shape to permit that is the first step.

I will be writing up some pages to explain what we are trying to do and outline a way forward, so we have a shared understanding and anyone in the community can raise concerns (if there are any) about the approach.

I really appreciate your efforts towards pushing / easing us to Python3 ;)  We stalled a bit there for a while, I think the concern was that updating Infogami was not part of out main mission, and would require a lot of effort. I feel now it is clearer to everyone that this is required, and we can move forward.

I want to have things set up in a way that will allow other contributors to push this forward too, so I will focus my efforts in the near term to make this happen.

I agree that getting CI passing for Python2 is the first priority. We also need to ensure that production OL is able to pull latest master with confidence, so it is critical that the tests are providing some real functional cover too.

**Comment by hornc** [comment]
@cclauss This fix is no longer required -- I have corrected course by backing out the merged changes affecting many files and not covered by testing which broke master and am trying to bring this repo into a state where we can all contribute effectively without risking Open Library production. Please bear with me while I make the changes. Thank you for your patience!

**Pull request closed without merging**
