### PR TITLE
Dict mixin to mapping

### PR DESCRIPTION
**Pull request by tfmorris**
Add missing abstract base class methods to #45

### CODE REVIEW

**Comment by tfmorris** [comment]
This is an improvement over the previous PR and shouldn't break Python 2, but there are some issues with the `markdown` module that I haven't been able to fully investigate. 

I suspect that we need to continue using our private fork and not attempt to switch to the PyPI version unless someone is able to investigate substantial time.

**Comment by cclauss** [comment]
> not attempt to switch to the PyPI version [_of web.py_] unless someone is able to investigate substantial time.

https://github.com/webpy/webpy/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed

**Comment by tfmorris** [comment]
@cclauss That's a misquote. I was referencing the PyPI version of `markdown`, not `web.py`. Was the switch to that intentional? I suspect it was a mistake (and the code appears to use both the local version and the PyPI version in different places). The private subclasses don't appear to work with either version currently, but I didn't have time to investigate why.

**Comment by cclauss** [comment]
Got it.  This PR was in a really bad git-state that @mekarpeles and @cdrini helped me to rectify.  That is now done and this PR only effects three files and in no way touches  markdown.

**Comment by tfmorris** [comment]
It looks like my commit 5974ec2 which adds the new methods has been rewritten and added to the other PR, (#45) so closing this for now.

**Comment by cclauss** [comment]
Your implementation of `__iter()__` (using yield) was much more Pythonic than mine (using a generator) so I did lift yours in 265d1b4dc08f632296a54da7e18f8594847c41e4.  Are you OK with #45  or should I close it in favor of #47 and then add the doctests after.  I am flexible.

**Comment by tfmorris** [comment]
@cclauss I'm happy leaving this one closed.

**Pull request closed without merging**
